### PR TITLE
Andi settingsv2

### PR DESCRIPTION
**Pull request by andi-halim**
[//]: # "These comments meant for your reference, they are invisible and don't need to be deleted"

## What's new in this PR?

[//]: # '####### YOUR ANSWER BELOW ###########'
User Profile / Settings Page MVP 1 done. 

### How to Review

[//]: # 'The order in which to review files and 
what to expect when testing locally'
[//]: # '####### YOUR ANSWER BELOW ###########'
Try changing your name to test functionality. (Edit -> Save)

### Related PRs

[//]: # "Optional - related PRs you're waiting on
/ PRs that will conflict, etc"
[//]: # '####### YOUR ANSWER BELOW ###########'
New PR for Settings. Can delete the other PR and its branch (tho it hasn't been done yet)

### Next steps

[//]: # "What doesn't work yet, what's NOT in this 
PR/has to be done "
[//]: # '####### YOUR ANSWER BELOW ###########'
Material UI not fully implemented as it works on front-end but functions/back-end not working as wanted with the Save/Edit.
- MVP 1 using normal buttons. 

### Screenshots

[//]: # '#### YOUR SCREENSHOTS BELOW ########'
image
image

### Design Status

[//]: # 'If this is a frontend PR, what is the expected 
status of the UI in this PR (lo, mid, high- fi?'
[//]: # '####### LOFI/MIDFI/HIFI ###########'
[//]: # '############## END ##################'

CC: @phoebeli23

### CODE REVIEW

**Comment by phoebeli23** [comment]
- Makes sense to for user email and organization to not be editable
- Airtable properly updates for first/last name
- Regarding MUI buttons: I believe you will need to add more props (namely onClick) to the EditButton class to get the click functionality working (pls work with Myles on this)

**Review by phoebeli23 — COMMENTED** [review]
- Airtable properly updates for first/last name
- Makes sense to for user email and organization to not be editable
- Regarding MUI buttons: I believe you will need to add more props (namely onClick) to the EditButton class to get the click functionality working (pls work with Myles on this)

**Comment by andi-halim** [comment]
> * Airtable properly updates for first/last name
> * Makes sense to for user email and organization to not be editable
> * Regarding MUI buttons: I believe you will need to add more props (namely onClick) to the EditButton class to get the click functionality working (pls work with Myles on this)

MUI buttons resolved. working now.

**Review by phoebeli23 — APPROVED** [review]
great work andi!

**Pull request merged**
